version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fullstack-app
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    restart: unless-stopped
